services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    env_file:
      - .env

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - "mongodb"

volumes:
  data: {}

networks:
  default:
    name: monogodb_network

